backend:
  name: github
  repo: jayyeung/portfolio-web
  branch: master

media_folder: 'static/content/assets'
public_folder: 'assets/images'

collections:
  - label: 'Case studies'
    name: 'case-study'
    label_singular: 'Case study'
    folder: 'static/content/case_studies'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: 'Project Link', name: 'project-link', widget: 'string'}
      - {label: 'Source Code', name: 'source', widget: 'string'}
      - {label: 'Content', name: 'content', widget: 'markdown'}