backend:
  name: github
  repo: jayyeung/portfolio-web
  branch: master

media_folder: 'static/content/assets'
public_folder: 'content/assets'

collections:
  - label: 'Case studies'
    name: 'case-study'
    label_singular: 'Case study'
    folder: 'static/content/case-studies'
    create: true
    fields:
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Thumbnail', name: 'thumbnail', widget: 'image', default: 'http://placehold.it/400x280'}
      - {label: 'Project Demo', name: 'project_demo', widget: 'file'}
      - {label: 'Project Type', name: 'project_type', widget: 'string'}
      - {label: 'Project Link', name: 'project_link', widget: 'string'}
      - {label: 'Source Code', name: 'source', widget: 'string'}
      - {label: 'Summary', name: 'summary', widget: 'text'}
      - {label: 'Content', name: 'body', widget: 'markdown'}