backend:
  name: github
  branch: master

media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

collections:
  - label: 'Case studies'
    name: 'case-study'
    label_singular: 'Case study'
    folder: '_studies'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Project Link', name: 'project-link', widget: 'string'}
      - {label: 'Source', name: 'source', widget: 'string'}
      - {label: 'Source', name: 'source', widget: 'string'}
